
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Sep 24 23:16:48 IST 2005
//----------------------------------------------------

package in.iitd.mldev.core.parse;

/** CUP generated class containing symbol constants. */
public class SmlSymbols {
  /* terminals */
  public static final int VAL = 46;
  public static final int INFIXR = 28;
  public static final int ORELSE = 36;
  public static final int LBRACKET = 53;
  public static final int WITH = 49;
  public static final int CHAR = 7;
  public static final int ASTERISK = 70;
  public static final int EQUALS = 66;
  public static final int SEMIC = 62;
  public static final int CASE = 12;
  public static final int HASH = 69;
  public static final int LPAREN = 51;
  public static final int INFIX = 27;
  public static final int INT = 4;
  public static final int WHERE = 47;
  public static final int BAR = 65;
  public static final int RPAREN = 52;
  public static final int REC = 38;
  public static final int AND = 9;
  public static final int FUN = 20;
  public static final int FN = 19;
  public static final int TYPE = 45;
  public static final int IN = 25;
  public static final int COMMA = 59;
  public static final int LAZY = 29;
  public static final int OP = 34;
  public static final int DATATYPE = 13;
  public static final int IF = 24;
  public static final int DOT = 58;
  public static final int ID = 2;
  public static final int COLONGT = 61;
  public static final int OF = 33;
  public static final int EOF = 0;
  public static final int UNDER = 64;
  public static final int RBRACKET = 55;
  public static final int TYVAR = 3;
  public static final int error = 1;
  public static final int INCLUDE = 26;
  public static final int EXCEPTION = 18;
  public static final int SHARING = 39;
  public static final int REAL = 5;
  public static final int ARROW = 68;
  public static final int FUNSIG = 22;
  public static final int COLON = 60;
  public static final int LBRACE = 56;
  public static final int ELSE = 15;
  public static final int DARROW = 67;
  public static final int ANDALSO = 10;
  public static final int WHILE = 48;
  public static final int EQTYPE = 17;
  public static final int DOTDOTDOT = 63;
  public static final int LET = 30;
  public static final int RBRACE = 57;
  public static final int THEN = 44;
  public static final int NONFIX = 32;
  public static final int LVECTOR = 54;
  public static final int SIG = 40;
  public static final int STRUCTURE = 43;
  public static final int OPEN = 35;
  public static final int FUNCTOR = 21;
  public static final int ABSTYPE = 8;
  public static final int END = 16;
  public static final int SIGNATURE = 41;
  public static final int STRING = 6;
  public static final int LOCAL = 31;
  public static final int AS = 11;
  public static final int STRUCT = 42;
  public static final int WITHTYPE = 50;
  public static final int HANDLE = 23;
  public static final int RAISE = 37;
  public static final int DO = 14;
}

